#!/bin/bash
# This script executes the hanger.lua script using Lua and passes along any arguments

# This script will be in path by the install script.

# Run the Lua script with all the passed arguments
lua ~/Hanger/src/Hanger.lua "$@"
